name: Deploy — Backend then Frontend

on:
  workflow_dispatch:
    inputs:
      aks_cluster_name:
        description: "AKS cluster name"
        required: true
      aks_resource_group:
        description: "AKS resource group"
        required: true
      aks_acr_name:
        description: "ACR name (e.g., myregistry)"
        required: true

jobs:
  backend:
    uses: ./.github/workflows/backend-cd.yml
    with:
      aks_cluster_name: ${{ inputs.aks_cluster_name }}
      aks_resource_group: ${{ inputs.aks_resource_group }}
      aks_acr_name: ${{ inputs.aks_acr_name }}
    secrets: inherit

  frontend:
    needs: backend
    uses: ./.github/workflows/frontend-cd.yml
    with:
      product_api_ip: ${{ needs.backend.outputs.product_ip }}
      order_api_ip: ${{ needs.backend.outputs.order_ip }}
      aks_cluster_name: ${{ inputs.aks_cluster_name }}
      aks_resource_group: ${{ inputs.aks_resource_group }}
    secrets: inherit
