name: Deploy — Backend then Frontend

on:
  workflow_dispatch:

jobs:
  backend:
    uses: ./.github/workflows/backend-cd.yml
    with:
      aks_cluster_name: "<aks_cluster_name>"
      aks_resource_group: "<resource_group_name>"
      aks_acr_name: "<acr_name>"
    secrets: inherit

  frontend:
    needs: backend
    uses: ./.github/workflows/frontend-cd.yml
    with:
      product_api_ip: ${{ needs.backend.outputs.product_ip }}
      order_api_ip: ${{ needs.backend.outputs.order_ip }}
      aks_cluster_name: "<aks_cluster_name>"
      aks_resource_group: "<resource_group_name>"
    secrets: inherit
